openapi: 3.0.3
info:
  title: "Service Publishing"
  description: "Service Publishing with Cloudflare."
  version: 0.4.0
  x-logo:
    url: "https://avatars.githubusercontent.com/u/140297229?s=400"
    backgroundColor: '#FFFFFF'
    altText: "Logo"
servers:
- url: https://localhost:80
tags:
- name: "Objects"
  x-displayName: "All Objects"
  description: |
    ## Service Publishing
    <SchemaDefinition schemaRef="#/components/schemas/service_publishing"/>
paths: {}
components:
  schemas:
    service_publishing:
      type: object
      description: "Service Publishing input object."
      properties:
        # Array of defined objects
        records:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/record'
        tunnels:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/tunnel'
        access_applications:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/access_application'
        access_policies:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/access_policy'
        access_service_tokens:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/access_service_token'
        spectrum_applications:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/spectrum_application'
        load_balancers:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/load_balancer'
    # Derived objects from upstream
    record:
      type: object
      allOf:
        # Base properties
        - $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/dns-records_dns-record'
        # Zone identifier
        - properties:
            zone_id:
              type: string
              $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/dns-records_identifier'
    tunnel:
      type: object
      allOf:
        - $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/tunnel_cfd_tunnel'
        - properties:
            account_id:
              type: string
              $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/tunnel_cf_account_id'
        - properties:
            config:
              type: object
              $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/tunnel_config'
    access_application:
      type: object
      allOf:
        - $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/access_apps'
        - properties:
            zone_id:
              type: string
              $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/access_identifier'
    access_policy:
      type: object
      allOf:
        - $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/access_schemas-policies'
        - properties:
            zone_id:
              type: string
              $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/access_identifier'
    access_service_token:
      type: object
      allOf:
        - $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/access_service-tokens'
        - properties:
            account_id:
              type: string
              $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/access_identifier'
    spectrum_application:
      type: object
      properties:
        zone_id:
          $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/access_identifier'
        name:
          $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/legacy-jhs_dns_name'
        protocol:
          $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/legacy-jhs_protocol'
        origin_direct:
          type: array
          description: "A list of destination addresses to the origin."
          example: "[\"tcp://192.0.2.1:22\"]"
          items:
            type: string
        origin_dns:
          $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/legacy-jhs_origin_dns'
        origin_port:
          $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/legacy-jhs_origin_port'
        tls:
          $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/legacy-jhs_tls'
    load_balancer:
      type: object
      allOf:
        - $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/load-balancing_load-balancer'
        - properties:
            zone_id:
              $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/load-balancing_load-balancer_components-schemas-identifier'
            default_pool:
              type: object
              description: "Default pool of the loadbalancer. Will be automatically added as fallback_pool as well."
              required:
                - name
                - origins
              properties:
                account_id:
                  $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/load-balancing_load-balancer_components-schemas-identifier'
                description:
                  $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/load-balancing_schemas-description'
                enabled:
                  $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/load-balancing_enabled'
                latitude:
                  $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/load-balancing_latitude'
                load_shedding:
                  $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/load-balancing_load_shedding'
                longitude:
                  $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/load-balancing_longitude'
                minimum_origins:
                  $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/load-balancing_minimum_origins'
                monitor:
                  $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/load-balancing_monitor-editable'
                name:
                  $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/load-balancing_name'
                notification_email:
                  $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/load-balancing_notification_email'
                notification_filter:
                  $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/load-balancing_notification_filter'
                origin_steering:
                  $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/load-balancing_origin_steering'
                origins:
                  $ref: 'https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml#/components/schemas/load-balancing_origins'
